---
# tasks file for register_to_satellite
- name: Check whether has been registered
  command: subscription-manager identity
  register: sub_mgr
  ignore_errors: true

- debug: msg="{{ sub_mgr }}"

- name: Download bootstrap.py from the {{ sat6_fqdn }}
  get_url:
    url: "http://{{ sat6_fqdn }}/pub/bootstrap.py"
    dest: /usr/local/sbin/bootstrap.py
  register: get_url_result
  until: get_url_result | succeeded
  retries: 10
  delay: 1
  ignore_errors: yes
  when: sub_mgr.rc == 1

- name: Copy bootstrap.py script to /usr/local/sbin and make it executable
  file:
    path: /usr/local/sbin/bootstrap.py
    mode: 0755
    owner: root
    group: root
  when: sub_mgr.rc == 1

- name: Register to Satellite6 with puppet *disabled* and add it to the correct hostgroup
  command: "/usr/local/sbin/bootstrap.py --skip puppet -l {{ admin_user}} -p {{ admin_pass }} -s {{ sat6_fqdn }} -o {{ org }} -L {{ loc }} -g {{ hostgroup }} -a {{ activationkey }}"
  when: sub_mgr.rc == 1

