---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  #remote_user: root
  # remote_user: user
  # sudo: yes
  become: yes

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
