---
# tasks file for foreman_scape_client
- set_fact:
   openscap_policies: "{{ openscap_policies_rhel6 }}"
  when: ansible_distribution_major_version|int == 6

- set_fact:
    openscap_policies: "{{ openscap_policies_rhel7 }}"
  when: ansible_distribution_major_version|int == 7

- name: Installing the OpenSCAP client
  yum:
    name: "rubygem-foreman_scap_client"
    enablerepo: "rhel-{{ ansible_distribution_major_version }}-server-satellite-tools-{{ satellite_version }}-rpms"
    state: latest

- name: Update /etc/foreman_scap_client/config.yaml
  template:
    src: "templates/config.yaml.j2"
    dest: /etc/foreman_scap_client/config.yaml

- name: Running the OpenSCAP client policies
  shell: "/usr/bin/foreman_scap_client {{ item.policy_id }}"
  with_items: "{{ openscap_policies }}"

- name: Creating OpenSCAP cron.d configuration for RHEL 7
  cron:
    name: "Generate OpenSCAP profile for profile {{ item.profile_id }}" 
    cron_file: /etc/cron.d/openscap
    job: /usr/bin/foreman_scap_client {{ item.policy_id }}
    user: root
    minute: "{{ minute }}"
    hour: "{{ hour }}"
    day: "{{ day }}" 
    weekday: "{{ weekday }}" 
    month: "{{ month }}" 
  state: present
  with_items: "{{ openscap_policies_rhel7 }}"
