---
- name: Launch EC2 instance
  ec2:
    region: "{{ ec2_server_region }}"
    group: "{{ ec2_server_security_group }}"
    keypair: "{{ ec2_server_keypair }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_server_image }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id}}"
    assign_public_ip: True
    wait: True
    wait_timeout: 600
    count: "{{ ec2_server_instcount }}"
    instance_tags:
      Name: "{{ ec2_server_name }}"
  register: ec2

- name: Instance Ids
  debug: msg={{ item.id }}
  with_items: "{{ ec2.instances }}"

- set_fact:
    new_vm_uuid: "{{ec2.instances[0].id}}"

- debug: var=new_vm_uuid

- name: Wait for SSH
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 25
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"

- name: Add hosts group temporary inventory group
  add_host:
    name: "{{ item.public_dns_name }}"
    group: " {{ec2_server_group_name }}"
  with_items: "{{ ec2.instances }}"
