- name: copy vhost file into nginx
  action: template src=www.conf.j2 dest=/etc/nginx/conf.d/www.conf mode=644
  notify: restart nginx

- name: make www path
  action: file dest={{www_root_path}} owner={{nginx_user}} state=directory mode=755

- name: write out index.html
  action: template src=index.html.j2 dest={{www_root_path}}/index.html mode=644



