- name: run ntpdate once
  action: command /usr/sbin/ntpdate ntp.ubuntu.com
  ignore_errors: yes

- name: set timezone
  action: copy src=timezone dest=/etc/timezone owner=root group=root mode=0644
  notify: reconfigure tzdata

- name: install common packages
  action: apt name=$item state=present update_cache=yes
  with_items:
    - vim
    - subversion
    - git
    - python-software-properties

