- hosts: localhost
  become: no
  gather_facts: yes
  
  tasks:
    - add_host:
        name: "{{ ip_address }}"
        groups: new-group
      when: ip_address is defined

- hosts: all
  become: yes
  gather_facts: yes
  
  roles:
    - ../roles/RHEL7-CIS
