- hosts: localhost
  become: no
  gather_facts: yes
  
  tasks:
    - add_host:
        name: "{{ ip_address }}"
      when: ip_address is defined

- hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - vars/oscap.yml

  roles:
    - { role: ../roles/oscap_scan, policy_id: "{{ openscap_policies_rhel7[0].policy_id }}" }
   