- hosts: localhost
  become: no
  gather_facts: yes
  
  tasks:
    - add_host:
        name: "{{ ip_address }}"
      when: ip_address is defined

- hosts: all
  become: yes
  gather_facts: yes
  #remote_user: cloud-user

  vars: 
    sat6_fqdn: "sat6.lab.ltsai.com"
    activationkey: "rhel-7Server,os_nginx"  
    admin_user: admin
    admin_pass: system
    org: IT
    loc: Primary-DC
    hostgroup: RHEL7-dev-nginx
    apply_updates: yes
  
  vars_files:
    - vars/oscap.yml

  roles:
    - ../roles/register_to_satellite
    - ../roles/foreman_scape_client