- hosts: all
  become: yes
  gather_facts: yes
  #remote_user: cloud-user

  vars: 
    sat6_fqdn: "sat6.lab.ltsai.com"
    activationkey: "rhel-7Server,os_nginx"  
    admin_user: admin
    admin_pass: system
    org: IT
    loc: Primary-DC
    hostgroup: RHEL7-dev-nginx
    apply_updates: yes
    
    openscap_policies_rhel7:
      - policy_id: 1
        profile_id: xccdf_org.ssgproject.content_profile_C2S
        content_path: /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
        download_path: /compliance/policies/1/content

  roles:
    - ../roles/register_to_satellite
    - ../roles/foreman_scape_client
    - { role: ../roles/oscap_scan, policy_id: "{{ openscap_policies_rhel7[0].policy_id }}" }
   