---
# defaults file for foreman_scape_client

foreman_proxy_server: sat6.lab.ltsai.com
foreman_proxy_port:   9090
ca_file:              /etc/rhsm/ca/katello-server-ca.pem
host_certificate:     /etc/pki/consumer/cert.pem
host_private_key:     /etc/pki/consumer/key.pem

satellite_version:    6.3

# cron settings At 02:00 on Sunday
minute: "0"
hour: "2"
day: "*"
month: "*"
weekday: "0"

openscap_policies_rhel6:
  - policy_id: 1
    profile_id: xccdf_org.ssgproject.content_profile_stig-rhel6-server-upstream
    content_path: /usr/share/xml/scap/ssg/content/ssg-rhel6-ds.xml
    download_path: /compliance/policies/1/content

openscap_policies_rhel7:
  - policy_id: 1
    profile_id: xccdf_org.ssgproject.content_profile_C2S
    content_path: /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
    download_path: /compliance/policies/1/content
