---
- name: Provision EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    - ec2_server_keypair: redhat_laptop
    - ec2_server_name: apache-demo
    - ec2_server_security_group: web-sg
    - ec2_vpc_subnet_id: subnet-00703749
    - ec2_server_group_name: mariadb-hosts
    - ec2_server_image: ami-f068a193
    - ec2_server_instcount: 2
    - name_start_index: 10
    - name_prefix: "VMANSADV"

    #Defaults in role
    #ec2_server_image: 'ami-f068a193' # Centos 7 in ap-southeast-1
    #ec2_server_region: ap-southeast-1
    #ec2_instance_type: t2.micro

    - ec2_tags:
        Deployment: DEV:PREP
        Project: ANSIBLE
        WBS_CODE: ISG18-B3B
        Vendor: RedHat

  roles:
    - create-ec2

- name: Install MariaDB
  hosts: mariadb-hosts
  become: yes

  vars:
    package_name: mariadb-server
    service_name: mariadb

  roles:
    - install-package
